endpoint: "wss://kusama-rpc.polkadot.io/"
port: 3000
logLevel: info
debug:
  enabled: false
  forceInitialWrite: false
exportDir: "./data-csv"
endSessionBlockDistance: 20
apiChunkSize: 3000
bucketUpload:
  enabled: false
  gcpServiceAccount: '~/Documents/serviceAccount.json'
  gcpProject: 'project-12345'
  gcpBucketName: 'my_bucket'
cronjob:
  enabled: false  